### PR TITLE
Fix(ui showjobs): redirect upload link to license module instead of b…

### LINKED ISSUE #514: Improving "legacy" browse view
There is the browse view for browsing through an upload. Actually, the user can get easily to there when she clicks a upload name / title in the "Show Jobs" view. Instead of the license browser, the user directly taken to there.

It could be good to have plan file view (see also the ticket https://github.com/fossology/fossology/issues/490) without the license extras)

Attached a screenshot to clarify which view is meant here:
2015-08-28 19_40_58-browse

### PR DESCRIPTION
**Pull request by Master-Gamer-glitch**
## Summary

This PR fixes the legacy browse redirection issue (#514) by updating the “Show Jobs” upload link to open the modern License Browser view instead of the legacy browse UI.

## Details

- Updated ui-showjobs.js to change the upload name anchor from:
        ```?mod=browse&upload=<id>&item=<id>```
      to:
        ```?mod=license&upload=<id>&item=<id>```

    - Verified that mod=license correctly loads the intended License Browser view without requiring additional redirects.
    - Preserved existing behavior for deleted uploads and other edge cases.
    - No functional changes beyond correcting the navigation target.

# Testing
 - Manually tested navigation from “Show Jobs”:
 -  Confirmed that clicking the upload name previously redirected to the legacy Browse view (?mod=browse).
 -  Manually changed the URL in the browser from mod=browse to mod=license and verified:
     - Page loads successfully
     - No permission errors
     - No console errors
     - License Browser UI renders correctly

  ## Applied the change locally:
   - Verified that clicking the upload name now directly loads the License Browser.
   - Confirmed breadcrumbs match expected License Browser behavior.
   - Verified no regressions in:
        - Pagination
        - Job action links
        - Other navigation flows

   Cleared cache and validated behavior after reload.

### Related Issue

- Closes #514

Notes

   - This change only updates the navigation mod parameter.
   - No database changes included.
   - No backend logic modified.

### CODE REVIEW

File: src/www/ui/template/ui-showjobs.js.twig [hunk 1]
```diff
@@ -98,7 +98,7 @@ function createTableForJob(job) {
   var uploadLink = "";
   if (job.upload !== null && job.upload.uploadItem != -1) {
     uploadLink = '<a title="{{ "Click to browse"|trans }}" ' +
-    'href="?mod=browse&upload=' + job.upload.uploadId + '&item=' +
+    'href="?mod=license&upload=' + job.upload.uploadId + '&item=' +
```
Comment (its-sushant) [inline src/www/ui/template/ui-showjobs.js.twig]:
```suggestion
    'href="?mod=fileBrowse&upload=' + job.upload.uploadId + '&item=' +
```
Please refer to this comment: https://github.com/fossology/fossology/issues/514#issuecomment-2975713616

**Review by its-sushant — CHANGES_REQUESTED** [review]
Please make the requested change and see the failing checks. Also the commit message should follow the commit convention: https://github.com/fossology/fossology/blob/master/CONTRIBUTING.md#git-commit

File: src/www/ui/template/ui-showjobs.js.twig (hunk 1 above)
Comment (Master-Gamer-glitch) [reply src/www/ui/template/ui-showjobs.js.twig]: Thank you for the review.

Updated the redirect to use `mod=fileBrowse` as suggested.
Also corrected the commit message to follow the commit convention and squashed the commits as well.

Please let me know if any further changes are required.

**Comment by its-sushant** [comment]
@Master-Gamer-glitch Commit msg is too long, please make it shorter. And commit should be verified and signed.
Check [here](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).

**Comment by Master-Gamer-glitch** [comment]
Shortened the commit message and signed the commit.

**Comment by its-sushant** [comment]
> Shortened the commit message and signed the commit.

Check the failing test.
