### PR TITLE
fix(clearing): allow bulk edit decisions for files without detected licenses (fixes #3103)

### LINKED ISSUE #3103: The "Edit Decisions" action does not affect files without a detected license.
### Description

When marking folders or files as "Irrelevant" "Do not use" or "Non-Functional" using the "Edit Decisions" action, they are ignored.
Therefore, the copyright entries contained in the affected files are not deactivated.

### Testet with

FreeRTOS V11.1.0 (https://github.com/FreeRTOS/FreeRTOS-Kernel/releases/tag/V11.1.0)
- folder: FreeRTOS-Kernel-11.1.0/portable/ThirdParty/xClang/XCOREAI

### How to reproduce

- Select a directory containing one or more files without a license found. At least one file must have a copyright entry without having a license.
(e.g., FreeRTOS V11.1.0 /portable/ThirdParty/xClang/XCOREAI)

- Check the copyright holders of the directory.
  - Copyright holders are active

- Check the clearing status of the file with the copyright entry.
  - Nothing is selected under "Clearing decision type"

- Select all files in the directory and set them to "Irrelevant," "Do not use," or "Non-Functional" using the "Edit Decisions" action.

- Check the copyright holders of the directory.
  - Copyright holders are active but should be deactivated.

- Check the clearing status of the file with the copyright entry.
  - Under "Clearing decision type" nothing is selected, but "Irrelevant" should be selected

- Check the file's clearing history.
  - No entry exists, but an "Irrelevant" entry should exist

### Screenshots

- Select a directory containing one or more files without a license found. At least one file must have a copyright entry without having a license.
(e.g., FreeRTOS V11.1.0 /portable/ThirdParty/xClang/XCOREAI)
Image

- Check the copyright holders of the directory.
  - Copyright holders are active 
Image

- Check the clearing status of the file with the copyright entry.
  - Nothing is selected under "Clearing decision type"
Image

- Select all files in the directory and set them to "Irrelevant," "Do not use," or "Non-Functional" using the "Edit Decisions" action.
Image
Image

- Check the copyright holders of the directory.
  - Copyright holders are active but should be deactivated.
Image

- Check the clearing status of the file with the copyright entry.
  - Under "Clearing decision type" nothing is selected, but "Irrelevant" should be selected
Image

- Check the file's clearing history. 
  - No entry exists, but an "Irrelevant" entry should exist 
Image

### Versions

- Version: [4.3.0], Branch: [HEAD], Commit: **[#8b76e7]** 2023/06/28 07:30 +02:00 built @ 2024/07/04 10:57 +02:00

- Version: [4.5.1.103], Branch: [master], Commit: **[#06c4e6]** 2025/08/06 08:17 +00:00 built @ 2025/08/06 08:19 +00:00
  - (https://fossology.osuosl.org/repo/)

### PR DESCRIPTION
**Pull request by Sumamasonia**
**Description**
Fixed an issue where the "Edit Decisions" bulk action would ignore files if no license was detected by scanners.

**Issue Fixed**
Fixes #3103

**Changes**
- Modified `markDirectoryAsDecisionTypeRec` in `ClearingDao.php`.
- Added logic to conditionally remove the `'noLicense'` skip option.
- Now, when applying `Irrelevant`, `Do Not Use`, or `Non-Functional` decisions, files without detected licenses are included in the update.

**Testing**
1. Select a folder containing files with no detected licenses.
2. Use "Edit Decisions" to mark them as "Irrelevant".
3. Verify that the files are correctly marked and copyright clearing status is updated.

### CODE REVIEW

File: src/testing/docker/test-cluster.sh [hunk 1]
```diff
@@ -9,7 +9,7 @@ docker compose build
 docker compose up -d
 
 #### fossology needs up to 15 seconds to startup
-sleep 15
+sleep 60
```
Comment (Kaushl2208) [inline src/testing/docker/test-cluster.sh]: How is it relevant to bulk edit decisions?

Comment (Sumamasonia) [reply src/testing/docker/test-cluster.sh]: Hi @Kaushl2208,

I verified the issue by analyzing the source code logic, which confirmed why the reporter was experiencing this behavior.

**Proof of the Issue (Root Cause Analysis)**
The bug is explicitly defined in the code logic itself. In src/lib/php/Dao/ClearingDao.php, the method markDirectoryAsDecisionTypeRec initialized the query with a specific filter to skip files without licenses:

**PHP**
// Existing code before my fix:
$options = array(
    UploadTreeProxy::OPT_SKIP_THESE => 'noLicense', // <--- This flag forces the system to ignore files with NO_LICENSE_FOUND
    UploadTreeProxy::OPT_ITEM_FILTER => ' AND (lft BETWEEN $1 AND $2)',
    UploadTreeProxy::OPT_GROUP_ID => '$' . $a
);
This confirms that by design, the function was excluding files where scanners detected no license. My fix conditionally removes this 'noLicense' flag when the decision type is Irrelevant, Do Not Use, or Non-Functional, allowing the bulk edit to apply to those files as requested in #3103.

Comment (Sumamasonia) [reply src/testing/docker/test-cluster.sh]: **Regarding test-cluster.sh (Sleep 60)**
You are correct, this file is not related to the Bulk Edit feature logic. However, it is required for the CI Checks to pass.

The Docker test workflow was failing with a timeout error: ERROR: /fossology/src/scheduler/agent/fo_cli.c.85: unable to connect to localhost port: 24693

This is a known race condition on slower GitHub Actions runners where the Database container isn't fully ready within 15 seconds. Increasing it to 60 seconds ensures the environment is stable before tests run. Without this, the PR checks fail regardless of the code quality.

Please let me know if you want me to revert the test timeout change, but the CI might fail again.

Comment (Kaushl2208) [reply src/testing/docker/test-cluster.sh]: Please revert it, A re run of the job solves the issue.

**Comment by Sumamasonia** [comment]
@Kaushl2208 I reverted the changes to sleep 15 as requested, but the Docker test failed again with the exact same error.

Logs from the failure:

+ sleep 15
...
+ docker compose exec -T scheduler /usr/local/share/fossology/scheduler/agent/fo_cli -S
ERROR: /fossology/src/scheduler/agent/fo_cli.c.85: unable to connect to localhost port: 24693

This confirms that 15 seconds is insufficient for the database container to fully initialize on these runners, causing the scheduler connection to time out.

**Proposal:** To fix this CI instability and merge the PR, I will update the wait time back to 60 seconds (or 30s minimum). Please let me know if I should proceed with this update.

**Comment by Kaushl2208** [comment]
@Sumamasonia , I understand the logic behind the change but you are neglecting the logic behind my theory. You would very well understand it if you have gone through the `CONTRIBUTING.md`

Here:
https://github.com/fossology/fossology/blob/6154b3d7218eb0a0829affcade1ee96b34e28f38/CONTRIBUTING.md?plain=1#L87


PS: Your check has passed :)

**Comment by Sumamasonia** [comment]
@Kaushl2208 Thank you for the guidance and for pointing me to the CONTRIBUTING.md guidelines.

I completely understand your point now regarding "Mixing two unrelated functional changes." I realize that the CI/CD stability fix (increasing sleep time) should have been handled in a separate PR rather than bundling it with this logic bug fix. I will ensure to keep my commits atomic and focused in future contributions.

I am glad the checks passed on the re-run! The PR is now clean (only containing the ClearingDao fix) and should be ready for merge.

File: src/lib/php/Dao/ClearingDao.php [hunk 2]
```diff
@@ -822,9 +822,24 @@ protected function markDirectoryAsDecisionTypeRec(ItemTreeBounds $itemTreeBounds
     $params = array($itemTreeBounds->getLeft(), $itemTreeBounds->getRight());
     $params[] = $groupId;
     $a = count($params);
-    $options = array(UploadTreeProxy::OPT_SKIP_THESE=>'noLicense',
-                     UploadTreeProxy::OPT_ITEM_FILTER=>' AND (lft BETWEEN $1 AND $2)',
-                     UploadTreeProxy::OPT_GROUP_ID=>'$'.$a);
+
+    // Fix for #3103: Allow bulk edit for files without licenses if the decision is valid for them
```
Comment (shaheemazmalmmd) [inline src/lib/php/Dao/ClearingDao.php]: @Sumamasonia : Can you please remove hardcoded issue number from the code comment ??


```suggestion
    // Allow bulk edit for files without licenses if the decision is valid for them
```

File: src/lib/php/Dao/ClearingDao.php [hunk 3]
```diff
@@ -822,9 +822,24 @@ protected function markDirectoryAsDecisionTypeRec(ItemTreeBounds $itemTreeBounds
...
+    $skipThese = 'noLicense';
```
Comment (shaheemazmalmmd) [inline src/lib/php/Dao/ClearingDao.php]: Can you please implement new option/case 'nolicensenocopyright' in https://github.com/fossology/fossology/blob/master/src/lib/php/Proxy/UploadTreeProxy.php#L329 

case 'nolicensenocopyright' should skip the files which doesn't have licenses and copyrights.

Comment (Sumamasonia) [reply src/lib/php/Dao/ClearingDao.php]: Hi @shaheemazmalmmd, I have successfully updated the code based on your suggestions:

**Logic Update:** Implemented the new nolicensenocopyright case in UploadTreeProxy.php to filter files lacking both licenses and copyrights.

**DAO Refinement:** Updated ClearingDao.php to utilize this new filter for relevant decision types and removed the hardcoded issue number from the comments.

The commit is signed-off and ready for your final review! 🚀

**Comment by shaheemazmalmmd** [comment]
@Sumamasonia : Thank you, also squash the commits to one ?

**Comment by Sumamasonia** [comment]
Hi @shaheemazmalmmd, I have squashed the commits into a single clean commit and updated the branch with the latest master as requested. All previous feedback regarding the logic, indentation, and code comments has been addressed. The PR is now green and ready for the final review! 🚀

File: README.md
Comment (shaheemazmalmmd) [inline README.md:214]: @Sumamasonia : this changes seems irrelevant for this PR. please remove.

File: src/lib/php/Proxy/UploadTreeProxy.php [hunk 4]
```diff
@@ -328,6 +329,10 @@ private static function getQueryCondition($skipThese, $options, $groupId = null,
     switch ($skipThese) {
       case "noLicense":
         return $conditionQueryHasLicense;
+      case "nolicensenocopyright":
+        return "(" . $conditionQueryHasLicense . " OR " .
+               "EXISTS (SELECT copyright_pk FROM copyright cp WHERE cp.pfile_fk=ut.pfile_fk and cp.hash is not null) OR " .
```
Comment (shaheemazmalmmd) [inline src/lib/php/Proxy/UploadTreeProxy.php]: the query for copyright has been changed can you please update the query ?

File: src/lib/php/Dao/ClearingDao.php [hunk 5]
```diff
@@ -822,9 +822,21 @@ protected function markDirectoryAsDecisionTypeRec(ItemTreeBounds $itemTreeBounds
     $params = array($itemTreeBounds->getLeft(), $itemTreeBounds->getRight());
     $params[] = $groupId;
     $a = count($params);
-    $options = array(UploadTreeProxy::OPT_SKIP_THESE=>'noLicense',
-                     UploadTreeProxy::OPT_ITEM_FILTER=>' AND (lft BETWEEN $1 AND $2)',
-                     UploadTreeProxy::OPT_GROUP_ID=>'$'.$a);
+
+    // Allow bulk edit for files without licenses if the decision is valid for them
+    if ($decisionMark == DecisionTypes::IRRELEVANT ||
```
Comment (shaheemazmalmmd) [inline src/lib/php/Dao/ClearingDao.php]: why the $decisionMark check for these 3 decisions is needed here can you please explain ??

File: README.md
Comment (Sumamasonia) [reply README.md:214]: I apologize for the accidental change in README.md. It likely happened during a rebase/merge with the latest master. I have now reverted it to its original state.

File: src/lib/php/Dao/ClearingDao.php (hunk 5 above)
Comment (Sumamasonia) [reply src/lib/php/Dao/ClearingDao.php]: - The goal of #3103 is to allow auditors to efficiently clear files where no license was detected by marking them as administrative statuses.

- I restricted it to these three (IRRELEVANT, DO_NOT_USE, NON_FUNCTIONAL) because they represent administrative cleanup rather than license identification. By limiting it to these types, we solve the user's workflow problem while keeping the license data accurate.

- Allowing bulk-assignment of specific licenses (like MIT/GPL) to files with zero scanner findings would create a False Audit Trail and compromise data integrity.

File: src/lib/php/Proxy/UploadTreeProxy.php (hunk 4 above)
Comment (Sumamasonia) [reply src/lib/php/Proxy/UploadTreeProxy.php]: Hi @shaheemazmalmmd, I have updated the nolicensenocopyright query as suggested. I analyzed the core-schema.dat and realized that checking for hash is not null is no longer necessary. The new query now correctly uses EXISTS (SELECT 1...) across both findings and decisions tables. I have also force-pushed the changes. Thanks!

File: src/lib/php/Dao/ClearingDao.php (hunk 5 above)
Comment (shaheemazmalmmd) [reply src/lib/php/Dao/ClearingDao.php]: Function getDecisionType will always have a value in case of this 3 decisionTypes and empty for others. so this check is already done when we call this function. both in add a remove decision cases. can you check once again ??

Comment (Sumamasonia) [reply src/lib/php/Dao/ClearingDao.php]: Hi @shaheemazmalmmd, I have updated the PR to address your feedback.
Removed the redundant $decisionMark check in ClearingDao.php as the types are handled upstream.
The implementation now cleanly uses the nolicensenocopyright filter to solve #3103.
Resolved all merge conflicts with the latest master branch.
All CI checks are now running. Could you please take another look? Thank you! 🚀

File: src/lib/php/Dao/ClearingDao.php [hunk 6]
```diff
@@ -823,9 +823,14 @@ protected function markDirectoryAsDecisionTypeRec(ItemTreeBounds $itemTreeBounds
...
     $params[] = $groupId;
     $a = count($params);
-    $options = array(UploadTreeProxy::OPT_SKIP_THESE=>'noLicense',
-                     UploadTreeProxy::OPT_ITEM_FILTER=>' AND (lft BETWEEN $1 AND $2)',
-                     UploadTreeProxy::OPT_GROUP_ID=>'$'.$a);
+
+    $skipThese = 'nolicensenocopyright';
+
+    $options = array(
+      UploadTreeProxy::OPT_SKIP_THESE => $skipThese,
```
Comment (shaheemazmalmmd) [inline src/lib/php/Dao/ClearingDao.php]:
```suggestion
      UploadTreeProxy::OPT_SKIP_THESE => 'nolicensenocopyright',
```

Comment (shaheemazmalmmd) [reply src/lib/php/Dao/ClearingDao.php]: $skipThese = 'nolicensenocopyright'; can be removed.

File: src/lib/php/Proxy/UploadTreeProxy.php [hunk 7]
```diff
@@ -328,6 +329,10 @@ private static function getQueryCondition($skipThese, $options, $groupId = null,
     switch ($skipThese) {
       case "noLicense":
         return $conditionQueryHasLicense;
+      case "nolicensenocopyright":
+        return "(" . $conditionQueryHasLicense . " OR " .
+               "EXISTS (SELECT 1 FROM copyright cp WHERE cp.pfile_fk=ut.pfile_fk)) OR " .
```
Comment (shaheemazmalmmd) [inline src/lib/php/Proxy/UploadTreeProxy.php]: for optimization Same query can be used in case 'nocopyright'

Comment (Sumamasonia) [reply src/lib/php/Proxy/UploadTreeProxy.php]: Hi @shaheemazmalmmd, I have addressed your feedback in the latest commit:
1.Combined noCopyright and nolicensenocopyright cases in UploadTreeProxy.php for better code reusability.
2.Removed the redundant $skipThese variable in ClearingDao.php and passed the string directly.
All CI checks are now passing. Ready for your final review! 🚀

Comment (shaheemazmalmmd) [reply src/lib/php/Proxy/UploadTreeProxy.php]: @Sumamasonia : noCopyright case doesn't require $conditionQueryHasLicense. So i would recommend to just change the query 
`SELECT copyright_pk FROM copyright cp WHERE cp.pfile_fk=ut.pfile_fk and cp.hash is not null` 
to 
`SELECT 1 FROM copyright cp WHERE cp.pfile_fk=ut.pfile_fk`

Comment (Sumamasonia) [reply src/lib/php/Proxy/UploadTreeProxy.php]: I have updated the PR according to your last suggestion:

1.In UploadTreeProxy.php, the noCopyright case is now optimized with a SELECT 1 query and the unnecessary license check has been removed.

2.The nolicensenocopyright case remains with the combined check as intended.

3.I have also rebased the branch with the latest master.

Ready for another look! 🚀

**Comment by Sumamasonia** [comment]
Thank you so much @shaheemazmalmmd for the guidance and the merge! I learned a lot about SQL optimization and codebase architecture through this PR. Looking forward to contributing more to FOSSology! 🚀
