### PR TITLE
fix(pkgagent): Avoid possible buffer overrun with strncpy

### LINKED ISSUE #1421: Warnings in building pkgagent on GCC8
### Logs

```lisp
pkgagent.c: In function 'ReadHeaderInfo':
pkgagent.c:461:11: warning: 'strncpy' specified bound 128 equals destination size [-Wstringop-truncation]
           strncpy(pi->buildDate,trim(asctime(gmtime((time_t*)tp))),sizeof(pi->buildDate));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
pkgagent.c: In function 'ProcessUpload':
pkgagent.c:378:7: warning: 'strncpy' specified bound 5000 equals destination size [-Wstringop-truncation]
       strncpy(dpi->pFile, PQgetvalue(result, i, 1), sizeof(dpi->pFile));
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
pkgagent.c:366:7: warning: 'strncpy' specified bound 5000 equals destination size [-Wstringop-truncation]
       strncpy(dpi->pFile, PQgetvalue(result, i, 1), sizeof(dpi->pFile));
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
pkgagent.c:348:7: warning: 'strncpy' specified bound 5000 equals destination size [-Wstringop-truncation]
       strncpy(pi->pFile, PQgetvalue(result, i, 1), sizeof(pi->pFile));
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by andi8086**
Copy BUFFSIZE-1 and add a 0 termination to the end.

Signed-off-by: Andreas J. Reichel <andreas.reichel@tngtech.com>

## Description

strncpy copies at most n bytes. If there is no 0-termination within these n bytes,
the destination string won't have any. Thus, copy BUFFSIZE-1 and add one in the
end in all occasions.

See the man page strncpy(3)

Closes #1421

### CODE REVIEW

File: src/pkgagent/agent/pkgagent.c [hunk 1]
```diff
@@ -458,7 +461,8 @@ void ReadHeaderInfo(Header header, struct rpmpkginfo *pi)
         case RPMTAG_BUILDTIME:
           t = atol(msgstr);
           tp = &t;
-          strncpy(pi->buildDate,trim(asctime(gmtime((time_t*)tp))),sizeof(pi->buildDate));
+          strncpy(pi->buildDate,trim(asctime(gmtime((time_t*)tp))),sizeof(pi->buildDate)-1);
+	  pi->buildDate[sizeof(pi->buildDate)-1] = '\0';
```
Comment (GMishx) [inline src/pkgagent/agent/pkgagent.c]: Please fix the indentation. Please use spaces instead of tabs.

Comment (andi8086) [reply src/pkgagent/agent/pkgagent.c]: Sorry, corrected.

**Comment by mcjaeger** [comment]
Hello, @GMishx I am not sure if "compiles without warnings" is enough for ready. I am uncertain if testing the code might be better?

**Comment by GMishx** [comment]
Hello @mcjaeger, I do agree that "compiles without warnings" is not good enough reason but the changes done in the PR does not alter any logic.

I have performed some manual testing on some of the branches as well and will leave another review comment with the test results.
