### PR TITLE
fix(scancode): Fixed failing scancode agent when using FOSSology in Docker

### LINKED ISSUE #2691: Docker: Permission denied: '/root/.cache'"
### Description

When using Fossology in a Docker I get error when scanner scans uploaded tarball

#### How to reproduce

1. docker run -p 8081:80 fossology/fossology
2. upload a tar ball - I used https://github.com/IBM/python-sdk-core/archive/refs/tags/v3.18.0.tar.gz but IMO any tarball will go.
3. Check the jobs.

the job of scancode agent fails with:

```
Log	

2024-03-01 09:55:35 scancode [0] :: JOB[10].scancode[644.localhost]: "Traceback (most recent call last):"
2024-03-01 09:55:35 scancode [0] :: JOB[10].scancode[644.localhost]: "  File "/usr/local/share/fossology/scancode/agent/runscanonfiles.py", line 11, in "
2024-03-01 09:55:35 scancode [0] :: JOB[10].scancode[644.localhost]: "    from scancode import api"
2024-03-01 09:55:35 scancode [0] :: JOB[10].scancode[644.localhost]: "  File "/home/fossy/pythondeps/scancode/__init__.py", line 16, in "
2024-03-01 09:55:35 scancode [0] :: JOB[10].scancode[644.localhost]: "    from commoncode import fileutils"
2024-03-01 09:55:35 scancode [0] :: JOB[10].scancode[644.localhost]: "  File "/home/fossy/pythondeps/commoncode/fileutils.py", line 21, in "
2024-03-01 09:55:35 scancode [0] :: JOB[10].scancode[644.localhost]: "    from scancode_config import scancode_temp_dir as _base_temp_dir"
2024-03-01 09:55:35 scancode [0] :: JOB[10].scancode[644.localhost]: "  File "/home/fossy/pythondeps/scancode_config.py", line 148, in "
2024-03-01 09:55:35 scancode [0] :: JOB[10].scancode[644.localhost]: "    _create_dir(scancode_cache_dir)"
2024-03-01 09:55:35 scancode [0] :: JOB[10].scancode[644.localhost]: "  File "/home/fossy/pythondeps/scancode_config.py", line 52, in _create_dir"
2024-03-01 09:55:35 scancode [0] :: JOB[10].scancode[644.localhost]: "    os.makedirs(location)"
2024-03-01 09:55:35 scancode [0] :: JOB[10].scancode[644.localhost]: "  File "/usr/lib/python3.9/os.py", line 215, in makedirs"
2024-03-01 09:55:35 scancode [0] :: JOB[10].scancode[644.localhost]: "    makedirs(head, exist_ok=exist_ok)"
2024-03-01 09:55:35 scancode [0] :: JOB[10].scancode[644.localhost]: "  File "/usr/lib/python3.9/os.py", line 215, in makedirs"
2024-03-01 09:55:35 scancode [0] :: JOB[10].scancode[644.localhost]: "    makedirs(head, exist_ok=exist_ok)"
2024-03-01 09:55:35 scancode [0] :: JOB[10].scancode[644.localhost]: "  File "/usr/lib/python3.9/os.py", line 225, in makedirs"
2024-03-01 09:55:35 scancode [0] :: JOB[10].scancode[644.localhost]: "    mkdir(name, mode)"
2024-03-01 09:55:35 scancode [0] :: JOB[10].scancode[644.localhost]: "PermissionError: [Errno 13] Permission denied: '/root/.cache'"
2024-03-01 09:55:35 scancode [0] :: JOB[10].scancode[644.localhost]: "FATAL ../src/scancode/agent/scancode_wrapper.cc.80: could not execute scancode command: PYTHONPATH='/home/fossy/pythondeps/' python3 runscanonfiles.py -l -m 50 /tmp/fileCEMUHS /tmp/filepeK0BU "
2024-03-01 09:55:35 scancode [0] :: JOB[10].scancode[644.localhost]: agent failed with error code 1
2024-03-01 09:55:35 scancode [0] :: JOB[10].scancode[644.localhost]: agent failed, code: 1
```
 
### Versions

Version: [4.4.0.7], Branch: [master], Commit: [#82757a] 2024/02/21 16:10 +00:00 built @ 2024/02/21 16:12 +00:00
Host is Fedora 39

### PR DESCRIPTION
**Pull request by dvjsharma**
## Description

When using FOSSology in Docker, the scancode agent fails to scan and throws a `Permission denied: '/root/.cache'` error.

This happens because scancode attempts to create a directory in `/root/.cache` while being initiated by the `fossy` user. To resolve this issue, scancode toolkit introduced various options as mentioned in [CHANGELOG.rst](https://github.com/nexB/scancode-toolkit/blob/66d71661f5ede54cb0f3b36d7663c92a67030299/CHANGELOG.rst#L2009-L2011) and [#2355](https://github.com/nexB/scancode-toolkit/issues/2355).  

### Changes

Introduced `SCANCODE_CACHE` environment variable in `runscanonfiles.py` file which holds the path to store cache (scancode agent directory in this case) which is accessible by `fossy` user.

## How to test
* Pull the changes and build the project using `docker compose up --build`.
* Upload any file (issue occured with tarball files, so preferably that) and schedule scancode agent under the section of scan selection.
* Scancode will run without fail. Images attached below (previous scan displays the error, latest scan shows the resolved result).

Screenshot from 2024-03-07 03-45-15

fixes #2691 #2667 
CC @GMishx

### CODE REVIEW

**Comment by dvjsharma** [comment]
Hey @GMishx, as discussed in the community meeting, I have updated the environment variable scope from the docker container to that specific file. I tested the changes, and everything is working as expected.

Screenshot from 2024-03-08 00-54-53
_Latest scan is without the changes, thus displaying an error. The previous scan includes the latest updates._

PTAL

File: src/scancode/agent/scancode_wrapper.cc [hunk 1]
```diff
@@ -70,6 +70,7 @@ void scanFileWithScancode(const State &state, string fileLocation, string output
 
   string command =
     "PYTHONPATH='/home/" + projectUser + "/pythondeps/' " +
+    "SCANCODE_CACHE='/usr/local/share/fossology/scancode/agent/.cache' " +
```
Comment (GMishx) [inline src/scancode/agent/scancode_wrapper.cc:73]: Ummm... Please do not hardcode the path like this here. It will change to `/usr/share/fossology` if installed as a `.deb` package.

Instead, I will recommend to use the `/home/<projectUser>/.cache` as it reads the username from config and is dynamic enough.

Alternatively, this variable can be moved to the `runscanonfiles.py` file and exported using `os.environ["SCANCODE_CACHE"]` and `__file__` variables.

**Review by GMishx — CHANGES_REQUESTED** [review]

File: src/scancode/agent/scancode_wrapper.cc (hunk 1 above)
Comment (dvjsharma) [reply src/scancode/agent/scancode_wrapper.cc:73]: Yea I shortly realized hardcoding path isn't the best way (or worst i'll say 🙂). Will make the changes soon.

**Comment by dvjsharma** [comment]
Hey @GMishx,

I have moved the variable into `runscanonfiles.py` file, as suggested. The cache location is now within the scancode agent directory itself (`fossy` user has access). Please note the environment variable needs to be set before importing `api` (tested) and hence its placement in the file. Scanner works as expected, results are attached below.

Screenshot from 2024-03-08 23-16-28

P1- Setting environment variable in `runscanonfiles.py` makes more sense than in docker\wrapper - Done.
P2- It's better to have the scancode agent directory to hold `.cache` directory - Done.

PTAL

**Review by GMishx — APPROVED** [review]
Changes looks good.

**Review by GMishx — APPROVED** [review]
Tested, working as expected.
