### PR TITLE
fix(dashboard): change comparison statements for postgres version

### LINKED ISSUE #1229: Empty Dashboard site
### Description

Dashboard shows empty page.

#### How to reproduce

1. `git clone https://github.com/fossology/fossology`
2. `cd fossology`
3. `docker-compose up -d`
4. When `docker-compose` finished, visit Fossology and login with `fossy` / `fossy`
5. Visit the Fossology site `/repo/?mod=dashboard`

### Versions

* Last commit id on master: `Version: [3.4.0], Branch: [master], Commit: [#1aed21] 2018/10/18 08:23 UTC built @ 2018/10/22 19:37 UTC`

* Operating System (lsb_release -a):

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
```

### PR DESCRIPTION
**Pull request by shaheemazmalmmd**
## Description

* removed STRCMP and added normal comparison method for PSQL comparison

### Changes

* removed STRCMP and added normal comparison method for PSQL comparison

## How to test

Install fossology on machines with different versions of POSTGRESQL and check the dashboard

closes #1229

### CODE REVIEW

File: src/www/ui/admin-dashboard.php [hunk 1]
```diff
@@ -226,9 +226,11 @@ function DatabaseQueries()
     $head3 = _("Started");
     $head4 = _("Elapsed");
     $V .= "<tr><th>$head1</th><th>$head2</th><th>$head3</th><th>$head4</th></tr>\n";
-
-    $current_query = (strcmp($this->pgVersion['server'], "9.2") >= 0) ? "state" : "current_query";
-    $procpid = (strcmp($this->pgVersion['server'], "9.2") >= 0) ? "pid" : "procpid";
+    $getCurrentVersion = explode(" ", $this->pgVersion['server']);
+    $currentVersion = str_replace(".", "", $getCurrentVersion[0]);
+    unset($getCurrentVersion);
+    $current_query = ($currentVersion >= "92") ? "state" : "current_query";
```
Comment (ag4ums) [inline src/www/ui/admin-dashboard.php]: better to define the version("9.2") as a variable instead of "92" for better understanding.

**Comment by ag4ums** [comment]
tested and reviewed code looks good.

File: src/www/ui/admin-dashboard.php [hunk 2]
```diff
@@ -226,9 +226,12 @@ function DatabaseQueries()
     $head3 = _("Started");
     $head4 = _("Elapsed");
     $V .= "<tr><th>$head1</th><th>$head2</th><th>$head3</th><th>$head4</th></tr>\n";
-
-    $current_query = (strcmp($this->pgVersion['server'], "9.2") >= 0) ? "state" : "current_query";
-    $procpid = (strcmp($this->pgVersion['server'], "9.2") >= 0) ? "pid" : "procpid";
+    $getCurrentVersion = explode(" ", $this->pgVersion['server']);
+    $currentVersion = str_replace(".", "", $getCurrentVersion[0]);
+    $oldVersion = str_replace(".", "", "9.2");
+    unset($getCurrentVersion);
```
Comment (maxhbr) [inline src/www/ui/admin-dashboard.php]: maybe move some lines up, directly under 30?

Why is the `unset` necessary?

Comment (shaheemazmalmmd) [reply src/www/ui/admin-dashboard.php]: because `$this->pgVersion['server']` creates string for postgres versions > 10
which looks like **10.0 (ubuntu 10.04 - ubuntu 18.04)** 
so when i explode this the array was creating 3 unnecessary values. apart from what i use. So used unset to empty the array once used.
