### PR TITLE
fix(api): enable JSON configuration support for external scanner agents

### LINKED ISSUE #2946: Can't use "scanoss": true to enable scanoss agent
My json includes scanoss agent, but not job runs with scanoss agent.
My version is 4.4.0.76
{
   "analysis": {
      "scanoss": true,
      "bucket": true,
      "copyright_email_author": true,
      "ecc": true,
      "keyword": true,
      "mime": true,
      "monk": true,
      "nomos": true,
      "package": true
   },
   "decider": {
      "nomos_monk": true,
      "new_scanner": true
   },
   "scancode": {
      "license": true,
      "copyright": true,
      "email": true,
      "url": true
   }
}

### PR DESCRIPTION
**Pull request by harshitg927**
## Description

Currently, several scanner agents cannot be enabled through the JSON configuration file despite being listed in the configuration. The affected agents are:
- SCANOSS
- IPRA
- OJO
- pkgagent
- Software Heritage

While these agents appear as `true` in the JSON configuration, they do not execute during job runs, making the configuration ineffective.

### Changes

Updated Analysis.php and ScanOptions.php to support all agents.

1. Analysis.php: Modified logic to ensure compatibility with all agents.
2. ScanOptions.php: Adjusted configurations to align with the changes in Analysis.php, also modified to be compatible with both version 1 of rest API as well as version 2 of rest API.

These updates enhance agent support and improve overall system robustness.

## How to test

1. Open any endpoint tester.
2. Test for POST request on either /jobs endpoint or /uploads endpoint with either queries or headers depending on the rest API version you are using.

## Screenshots

Screenshot from 2025-02-03 14-29-26

Screenshot from 2025-02-03 14-29-41

Fixes #2946

### CODE REVIEW

File: src/www/ui/api/Models/Analysis.php [hunk 1]
```diff
@@ -86,12 +101,15 @@ class Analysis
...
+   * @param boolean $scanoss
    * @param boolean $reso
    * @param boolean $pkgagent
+   * @param boolean $ipra
+   * @param boolean $softwareHeritage
    * @param boolean $compatibility
    */
   public function __construct($bucket = false, $copyright = false, $ecc = false, $keyword = false,
-    $mimetype = false, $monk = false, $nomos = false, $ojo = false, $reso = false, $pkgagent = false, $compatibility = false)
+    $mimetype = false, $monk = false, $nomos = false, $ojo = false, $scanoss = false, $reso = false, $pkgagent = false, $ipra = false, $compatibility = false)
```
Comment (GMishx) [inline src/www/ui/api/Models/Analysis.php:112]: New parameters must always be added at the end of parameter list.

File: src/www/ui/api/Models/Analysis.php [hunk 2]
```diff
@@ -141,13 +162,24 @@ public function setUsingArray($analysisArray, $version = ApiVersion::V1)
...
     if (array_key_exists("package", $analysisArray)) {
       $this->pkgagent = filter_var($analysisArray["package"],
         FILTER_VALIDATE_BOOLEAN);
     }
+    if (array_key_exists("patent", $analysisArray)) {
+      $this->ipra = filter_var($analysisArray["patent"],
+        FILTER_VALIDATE_BOOLEAN);
+    }
+    if (array_key_exists("heritage", $analysisArray)) {
+      $this->softwareHeritage = filter_var($analysisArray["heritage"],
```
Comment (GMishx) [inline src/www/ui/api/Models/Analysis.php:180]:
```suggestion
    if (array_key_exists("ipra", $analysisArray)) {
      $this->ipra = filter_var($analysisArray["ipra"],
        FILTER_VALIDATE_BOOLEAN);
    }
    if (array_key_exists("softwareHeritage", $analysisArray)) {
      $this->softwareHeritage = filter_var($analysisArray["softwareHeritage"],
```

Please keep naming consistent.

File: src/www/ui/api/Models/Analysis.php [hunk 3]
```diff
@@ -392,8 +478,11 @@ public function getArray($version = ApiVersion::V1)
         "monk"      => $this->monk,
         "nomos"     => $this->nomos,
         "ojo"       => $this->ojo,
+        "scanoss"   => $this->scanoss,
         "reso"      => $this->reso,
         "package"   => $this->pkgagent,
+        "patent"    => $this->ipra,
+        "heritage" => $this->softwareHeritage,
```
Comment (GMishx) [inline src/www/ui/api/Models/Analysis.php:485]:
```suggestion
        "ipra"    => $this->ipra,
        "softwareHeritage" => $this->softwareHeritage,
```

Please keep naming consistent.

File: src/www/ui/api/Models/Analysis.php [hunk 4]
```diff
@@ -406,8 +495,11 @@ public function getArray($version = ApiVersion::V1)
...
```
Comment (GMishx) [inline src/www/ui/api/Models/Analysis.php:502]:
```suggestion
        "ipra"    => $this->ipra,
        "softwareHeritage" => $this->softwareHeritage,
```

File: src/www/ui/api/Models/ScanOptions.php [hunk 5]
```diff
@@ -128,20 +128,54 @@ public function scheduleAgents($folderId, $uploadId , $newUpload = true)
...
-          $request->request->set("Check_agent_$agent", 1);
+
+    $uri = $_SERVER['REQUEST_URI'];
+    $apiVersion = ApiVersion::V1;
+
+    if (strpos($uri, '/api/v2/') !== false) {
+      $apiVersion = ApiVersion::V2;
+    }
+
+    if($apiVersion == ApiVersion::V2) {
```
Comment (GMishx) [inline src/www/ui/api/Models/ScanOptions.php:139]: Please do not implement custom code for something which already exists. You can check the version as bellow

```php
if (ApiVersion::getVersion($request) == ApiVersion::V2)
```

File: src/www/ui/api/Models/ScanOptions.php [hunk 6]
```diff
@@ -128,20 +128,54 @@ public function scheduleAgents($folderId, $uploadId , $newUpload = true)
...
+      foreach ($this->analysis->getArray($apiVersion) as $agent => $set) {
+        if ($set === true) {
+          if ($agent == "copyrightEmailAuthor") {
+            $agentsToAdd[] = "agent_copyright";
+            $request->request->set("Check_agent_copyright", 1);
+          } elseif ($agent == "patent") {
```
Comment (GMishx) [inline src/www/ui/api/Models/ScanOptions.php:145]:
```suggestion
          } elseif ($agent == "ipra") {
```

File: src/www/ui/api/Models/ScanOptions.php [hunk 7]
```diff
@@ -128,20 +128,54 @@ public function scheduleAgents($folderId, $uploadId , $newUpload = true)
...
+            $agentsToAdd[] = "agent_ipra";
+            $request->request->set("Check_agent_ipra", 1);
+          } elseif ($agent == "package") {
+            $agentsToAdd[] = "agent_pkgagent";
+            $request->request->set("Check_agent_pkgagent", 1);
+          } elseif ($agent == "heritage") {
```
Comment (GMishx) [inline src/www/ui/api/Models/ScanOptions.php:151]:
```suggestion
          } elseif ($agent == "softwareHeritage") {
```

File: src/www/ui/api/Models/ScanOptions.php [hunk 8]
```diff
@@ -128,20 +128,54 @@ public function scheduleAgents($folderId, $uploadId , $newUpload = true)
...
+          }
+        }
+      }
+    } else {
+      foreach ($this->analysis->getArray($apiVersion) as $agent => $set) {
+        if ($set === true) {
+          if ($agent == "copyright_email_author") {
+            $agentsToAdd[] = "agent_copyright";
+            $request->request->set("Check_agent_copyright", 1);
+          } elseif ($agent == "patent") {
```
Comment (GMishx) [inline src/www/ui/api/Models/ScanOptions.php:166]:
```suggestion
          } elseif ($agent == "ipra") {
```

File: src/www/ui/api/Models/ScanOptions.php [hunk 9]
```diff
@@ -128,20 +128,54 @@ public function scheduleAgents($folderId, $uploadId , $newUpload = true)
...
+            $agentsToAdd[] = "agent_ipra";
+            $request->request->set("Check_agent_ipra", 1);
+          } elseif ($agent == "package") {
+            $agentsToAdd[] = "agent_pkgagent";
+            $request->request->set("Check_agent_pkgagent", 1);
+          } elseif ($agent == "heritage") {
```
Comment (GMishx) [inline src/www/ui/api/Models/ScanOptions.php:172]:
```suggestion
          } elseif ($agent == "softwareHeritage") {
```

**Review by GMishx — CHANGES_REQUESTED** [review]
Thanks for your contribution!

Please check the suggestions and update the openapi.yaml and openapiv2.yaml files as well.

File: src/www/ui/api/Models/Analysis.php [hunk 10]
```diff
@@ -86,12 +101,15 @@ class Analysis
    * @param boolean $nomos
    * @param boolean $pkgagent
    * @param boolean $ojo
+   * @param boolean $scanoss
    * @param boolean $reso
    * @param boolean $pkgagent
+   * @param boolean $ipra
+   * @param boolean $softwareHeritage
    * @param boolean $compatibility
```
Comment (dvjsharma) [inline src/www/ui/api/Models/Analysis.php:109]: New parameters should be added at last in the comments as well.

File: src/www/ui/api/Models/Analysis.php [hunk 11]
```diff
@@ -274,11 +323,27 @@ public function getReso()
   /**
    * @return boolean
    */
-  public function getPackage()
+  public function getPkgagent()
```
Comment (dvjsharma) [inline src/www/ui/api/Models/Analysis.php:326]: Any reason for this change?

File: src/www/ui/api/Models/Analysis.php [hunk 12]
```diff
@@ -363,9 +436,22 @@ public function setReso($reso)
   /**
    * @param boolean $package
    */
-  public function setPackage($package)
+  public function setPkgagent($pkgagent)
```
Comment (dvjsharma) [inline src/www/ui/api/Models/Analysis.php:439]: Ditto

File: src/www/ui/api/Models/Analysis.php [hunk 13]
```diff
@@ -406,8 +495,11 @@ public function getArray($version = ApiVersion::V1)
         "monk"      => $this->monk,
         "nomos"     => $this->nomos,
         "ojo"       => $this->ojo,
+        "scanoss"   => $this->scanoss,
         "reso"      => $this->reso,
-        "package"   => $this->pkgagent,
+        "pkgagent"   => $this->pkgagent,
+        "ipra"    => $this->ipra,
+        "softwareHeritage" => $this->softwareHeritage,
```
Comment (dvjsharma) [inline src/www/ui/api/Models/Analysis.php:502]: You'll need to review unit test cases for `Analysis` model as well to accommodate new changes.
Ref: https://github.com/fossology/fossology/blob/master/src/www/ui_tests/api/Models/AnalysisTest.php

**Review by dvjsharma — CHANGES_REQUESTED** [review]
Hey @harshitg927. PTAL at the comments.

File: src/www/ui/api/Models/Analysis.php (hunk 1 above)
Comment (harshitg927) [reply src/www/ui/api/Models/Analysis.php]: done

File: src/www/ui/api/Models/Analysis.php (hunk 2 above)
Comment (harshitg927) [reply src/www/ui/api/Models/Analysis.php]: done

File: src/www/ui/api/Models/Analysis.php (hunk 3 above)
Comment (harshitg927) [reply src/www/ui/api/Models/Analysis.php]: done

File: src/www/ui/api/Models/ScanOptions.php (hunk 5 above)
Comment (harshitg927) [reply src/www/ui/api/Models/ScanOptions.php]: done

File: src/www/ui/api/Models/ScanOptions.php (hunk 6 above)
Comment (harshitg927) [reply src/www/ui/api/Models/ScanOptions.php]: done

File: src/www/ui/api/Models/ScanOptions.php (hunk 7 above)
Comment (harshitg927) [reply src/www/ui/api/Models/ScanOptions.php]: done

File: src/www/ui/api/Models/ScanOptions.php (hunk 8 above)
Comment (harshitg927) [reply src/www/ui/api/Models/ScanOptions.php]: done

File: src/www/ui/api/Models/ScanOptions.php (hunk 9 above)
Comment (harshitg927) [reply src/www/ui/api/Models/ScanOptions.php]: done

File: src/www/ui/api/Models/Analysis.php (hunk 11 above)
Comment (harshitg927) [reply src/www/ui/api/Models/Analysis.php:326]: This change was done to ensure consistent naming convention throughout the file.

File: src/www/ui/api/Models/Analysis.php (hunk 12 above)
Comment (harshitg927) [reply src/www/ui/api/Models/Analysis.php:439]: This change was also done to ensure consistent naming convention throughout the file.

File: src/www/ui/api/Models/Analysis.php (hunk 13 above)
Comment (harshitg927) [reply src/www/ui/api/Models/Analysis.php:502]: Sure, I will get on it. Thank you for the review.

File: src/www/ui/api/Models/Analysis.php (hunk 10 above)
Comment (harshitg927) [reply src/www/ui/api/Models/Analysis.php]: done

**Review by Kaushl2208 — CHANGES_REQUESTED** [review]

File: src/www/ui/api/Models/Analysis.php (hunk 13 above)
Comment (harshitg927) [reply src/www/ui/api/Models/Analysis.php:504]: Hello @dvjsharma , I have updated the test cases for the changes I have made in the Pull Request, please review them too. Thank you.

File: src/www/ui/api/Models/Analysis.php [hunk 14]
```diff
@@ -141,11 +161,22 @@ public function setUsingArray($analysisArray, $version = ApiVersion::V1)
...
+      $this->pkgagent = filter_var($analysisArray["pkgagent"],
+        FILTER_VALIDATE_BOOLEAN);
+    }
+    if (array_key_exists("ipra", $analysisArray)) {
+      $this->ipra = filter_var($analysisArray["ipra"],
+        FILTER_VALIDATE_BOOLEAN);
+    }
+    if (array_key_exists("softwareHeritage", $analysisArray)) {
+      $this->softwareHeritage = filter_var($analysisArray["softwareHeritage"],
         FILTER_VALIDATE_BOOLEAN);
```
[the remark this answers is not in the document]
Comment (harshitg927) [reply src/www/ui/api/Models/Analysis.php:180]: Hello @Kaushl2208 , thanks for the feedback. This actually makes a lot of sense, this will surely make the code more readable and maintainable. I will surely implement this and will push the changes as soon as possible.

[the remark this answers is not in the document]
Comment (harshitg927) [reply src/www/ui/api/Models/Analysis.php]: @Kaushl2208 I have commited the changes for this request, and I have also implemented a similar approach in the setUsingString method for better maintainability and readability of code, Please review these changes too. Thank You.

File: src/www/ui/api/Models/ScanOptions.php (hunk 5 above)
Comment (harshitg927) [reply src/www/ui/api/Models/ScanOptions.php]: Hello @GMishx ,
The getVersion() utility in ApiVersion model was limited to PSR-7 Requests. Added getVersionFromUri() method that works with both PSR-7 and Symfony Requests to resolve version detection in ScanOptions.php.
Changes tested and working as expected. Please review.
Thank You.

File: src/www/ui_tests/api/Models/AnalysisTest.php [hunk 15]
```diff
@@ -74,11 +80,23 @@ private function testSetUsingArray($version)
...
       ];
     }
 
     $expectedObject = new Analysis(true, true, true, true);
+    $expectedObject->setScanoss(true);
+    $expectedObject->setReso(true);
+    $expectedObject->setPkgagent(false);
+    $expectedObject->setIpra(true);
+    $expectedObject->setSoftwareHeritage(true);
+    $expectedObject->setCompatibility(false);
```
Comment (dvjsharma) [inline src/www/ui_tests/api/Models/AnalysisTest.php:99]: These can be passed directly in `Analysis` object.

File: src/www/ui_tests/api/Models/AnalysisTest.php [hunk 16]
```diff
@@ -94,26 +112,20 @@ private function testSetUsingArray($version)
...
-    $this->assertEquals($expectedObjectSemi, $actualObjectSemi);
+    $analysisString = "bucket, ecc, keyword, scanoss, ipra, softwareHeritage";
+
+    $expectedObject = new Analysis();
+    $expectedObject->setBucket(true);
+    $expectedObject->setEcc(true);
+    $expectedObject->setKeyword(true);
+    $expectedObject->setScanoss(true);
+    $expectedObject->setIpra(true);
+    $expectedObject->setSoftwareHeritage(true);
```
Comment (dvjsharma) [inline src/www/ui_tests/api/Models/AnalysisTest.php:123]: Ditto

File: src/www/ui_tests/api/Models/AnalysisTest.php [hunk 17]
```diff
@@ -149,40 +161,52 @@ private function testDataFormat($version)
...
+        "keyword" => false,
+        "mimetype" => true,
+        "monk" => false,
+        "nomos" => true,
+        "ojo" => true,
+        "scanoss" => true,
+        "reso" => true,
+        "pkgagent" => false,
+        "ipra" => true,
+        "softwareHeritage" => true,
```
Comment (dvjsharma) [inline src/www/ui_tests/api/Models/AnalysisTest.php:176]: Irrelevant change, please fix the spacing.

File: src/www/ui_tests/api/Models/AnalysisTest.php [hunk 18]
```diff
@@ -149,40 +161,52 @@ private function testDataFormat($version)
...
+        "keyword" => false,
+        "mimetype" => true,
+        "monk" => false,
+        "nomos" => true,
+        "ojo" => true,
+        "scanoss" => true,
+        "reso" => true,
+        "package" => false,
+        "patent" => true,
+        "heritage" => true,
```
Comment (dvjsharma) [inline src/www/ui_tests/api/Models/AnalysisTest.php:193]: Ditto

File: src/www/ui_tests/api/Models/UserTest.php [hunk 19]
```diff
@@ -159,7 +162,10 @@ private function testDataFormat($version)
           "monk"      => false,
           "nomos"     => true,
           "ojo"       => true,
-          "package"   => false,
+          "pkgagent"   => false,
+          "ipra" => false,
+          "softwareHeritage" => false,
+          "scanoss" => false,
```
Comment (dvjsharma) [inline src/www/ui_tests/api/Models/UserTest.php:168]: Please fix spacing.

File: src/www/ui_tests/api/Models/ScanOptionsTest.php
Comment (dvjsharma) [inline src/www/ui_tests/api/Models/ScanOptionsTest.php:1]: This is still failing in CI. PTAL.

**Review by dvjsharma — CHANGES_REQUESTED** [review]
Hey @harshitg927. Left few comments, PTAL.

File: src/www/ui_tests/api/Models/AnalysisTest.php (hunk 15 above)
Comment (harshitg927) [reply src/www/ui_tests/api/Models/AnalysisTest.php]: done

File: src/www/ui_tests/api/Models/AnalysisTest.php (hunk 16 above)
Comment (harshitg927) [reply src/www/ui_tests/api/Models/AnalysisTest.php:117]: done

File: src/www/ui_tests/api/Models/AnalysisTest.php (hunk 17 above)
Comment (harshitg927) [reply src/www/ui_tests/api/Models/AnalysisTest.php]: done

File: src/www/ui_tests/api/Models/AnalysisTest.php (hunk 18 above)
Comment (harshitg927) [reply src/www/ui_tests/api/Models/AnalysisTest.php]: done

File: src/www/ui_tests/api/Models/UserTest.php (hunk 19 above)
Comment (harshitg927) [reply src/www/ui_tests/api/Models/UserTest.php]: done

**Comment by harshitg927** [comment]
@dvjsharma I have fixed the failing test cases too, Please review the changes.

**Review by dvjsharma — APPROVED** [review]
Changes looks good. Tested, working as expected. Thank you for the contribution @harshitg927!

CC @GMishx @Kaushl2208

**Comment by harshitg927** [comment]
Hey @dvjsharma . As discussed on slack, I've added the new testcases as well. Please review it again.
