### PR TITLE
fix(buckets): Prevent possible buffer overflow/-run

### LINKED ISSUE #1417: Warnings in building buckets on GCC8
### Logs

```lisp
liccache.c: In function ‘add2license_ref’:
liccache.c:277:71: warning: ‘%s’ directive writing up to 255 bytes into a region of size 206 [-Wformat-overflow=]
     sprintf(query, "SELECT rf_pk FROM license_ref where rf_shortname='%s' and rf_detector_type=2", escLicName);
                                                                       ^~                           ~~~~~~~~~~
liccache.c:277:5: note: ‘sprintf’ output between 75 and 330 bytes into a destination of size 256
     sprintf(query, "SELECT rf_pk FROM license_ref where rf_shortname='%s' and rf_detector_type=2", escLicName);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
liccache.c:291:87: warning: ‘%s’ directive writing up to 255 bytes into a region of size 183 [-Wformat-overflow=]
             "insert into license_ref(rf_shortname, rf_text, rf_detector_type) values('%s', '%s', 2)",
                                                                                       ^~
             escLicName, specialLicenseText);
             ~~~~~~~~~~                                                                 
liccache.c:290:5: note: ‘sprintf’ output between 100 and 355 bytes into a destination of size 256
     sprintf( insert,
     ^~~~~~~~~~~~~~~~
             "insert into license_ref(rf_shortname, rf_text, rf_detector_type) values('%s', '%s', 2)",
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             escLicName, specialLicenseText);
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
walk.c: In function ‘processFile’:
walk.c:225:7: warning: ‘strncpy’ specified bound 256 equals destination size [-Wstringop-truncation]
       strncpy(package.pkgname, PQgetvalue(result, 0, 0), sizeof(package.pkgname));
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
walk.c:229:7: warning: ‘strncpy’ specified bound 256 equals destination size [-Wstringop-truncation]
       strncpy(package.pkgvers, PQgetvalue(result, 0, 1), sizeof(package.pkgvers));
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
walk.c:233:7: warning: ‘strncpy’ specified bound 256 equals destination size [-Wstringop-truncation]
       strncpy(package.vendor, PQgetvalue(result, 0, 2), sizeof(package.vendor));
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
walk.c:237:7: warning: ‘strncpy’ specified bound 256 equals destination size [-Wstringop-truncation]
       strncpy(package.srcpkgname, PQgetvalue(result, 0, 3), sizeof(package.srcpkgname));
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by andi8086**
Allocate enough space for sprintf, use strncpy correctly to be sure
to have a 0 at the end of the dest buffer.

Signed-off-by: Andreas J. Reichel <andreas.reichel@tngtech.com>

## Description

Closes #1417

### CODE REVIEW

File: src/buckets/agent/liccache.c [hunk 1]
```diff
@@ -257,8 +257,8 @@ FUNCTION long get_rfpk(PGconn *pgConn, cacheroot_t *pcroot, char *rf_shortname)
 FUNCTION long add2license_ref(PGconn *pgConn, char *licenseName)
 {
     PGresult *result;
-    char  query[256];
-    char  insert[256];
+    char  query[512];
+    char  insert[512];
```
Comment (GMishx) [inline src/buckets/agent/liccache.c]: Will it be a good idea to use `MAXSQL` like https://github.com/fossology/fossology/blob/bd139437c967d88313d7259915be103d25d3712d/src/delagent/agent/util.c#L111 ?

Also, please change following `sprintf`s to `snprintf`s accordingly.

Comment (andi8086) [reply src/buckets/agent/liccache.c]: Yes.
