### PR TITLE
fix(AdviceLicense): Show error message on failure

### LINKED ISSUE #938: LicenseCandidates:Error in merging/verifiying-Prozess
In the course of inserting a new license I received the following error on cli: 

fossology-db_1          | LOG:  could not receive data from client: Connection reset by peer
fossology-db_1          | ERROR:  duplicate key value violates unique constraint "rf_md5unique"
fossology-db_1          | DETAIL:  Key (rf_md5)=(36ef664ecb655e91bf32c72773ce05d5) already exists.
fossology-db_1          | STATEMENT:  INSERT INTO license_ref (rf_pk, rf_shortname, rf_text, rf_url, rf_add_date, rf_copyleft,
fossology-db_1          | 	        "rf_OSIapproved", rf_fullname, "rf_FSFfree", "rf_GPLv2compatible", "rf_GPLv3compatible", rf_notes, "rf_Fedora",
fossology-db_1          | 	        marydone, rf_active, rf_text_updatable, rf_md5 , rf_detector_type, rf_risk)
fossology-db_1          | 	      (SELECT rf_pk, $2 as rf_shortname, rf_text, rf_url, now() as rf_add_date, rf_copyleft,
fossology-db_1          | 	        "rf_OSIapproved", rf_fullname, "rf_FSFfree", "rf_GPLv2compatible", "rf_GPLv3compatible", rf_notes, "rf_Fedora",
fossology-db_1          | 	        false AS marydone, rf_active, rf_text_updatable, md5(rf_text) rf_md5 , 1 rf_detector_type, rf_risk
fossology-db_1          | 	  FROM license_candidate WHERE rf_pk=$1)
fossology-web_1         | [Thu Nov 09 07:38:04.622045 2017] [:error] [pid 19] [client 172.18.0.1:52126] PHP Warning:  pg_execute(): Query failed: ERROR:  duplicate key value violates unique constraint &quot;rf_md5unique&quot;\nDETAIL:  Key (rf_md5)=(36ef664ecb655e91bf32c72773ce05d5) already exists. in /usr/local/share/fossology/lib/php/Db/Driver/Postgres.php on line 72, referer: http://localhost:8081/repo/?mod=admin_license_candidate&rf=601
fossology-web_1         | [Thu Nov 09 07:38:04.622247 2017] [:error] [pid 19] [client 172.18.0.1:52126] [2017-11-09 07:38:04] default.CRITICAL: ERROR:  duplicate key value violates unique constraint "rf_md5unique" DETAIL:  Key (rf_md5)=(36ef664ecb655e91bf32c72773ce05d5) already exists. [] [], referer: http://localhost:8081/repo/?mod=admin_license_candidate&rf=601

Usually I use the WebUI working on fossology. I'm trying to test all functionallity on UI to learn, how fossology work.  

Where is my mistake. Sometimes it works, and sometimes not. 
As I understood, the process of adding a new license is to create new license on "organize -> Licenses -> new license". After adding I turn to the page "Admin -> License Admin -> Candidates"  and trying to verify or merge or compare. 

What I also ask myself is whether it's the right thing to do, or whether I have to set up adding somewhere else the license. My goal is not only to add new license, but also to replace, for instance "unknown license". Any Idea? 
Thanks in advance

### LINKED ISSUE #1507: Show error message if advice license verify fails
### Description

While trying to verify a advice license to be merged, if the license text from advice license already exists in any of the main license, the MD5 constraint fails at the DB and the user gets a blank page.

In such cases, the user should be shown an error message but FOSSology returns a blank page which left user confused why the request failed.

#### How to reproduce

1. Create a new advice license with license text as one of the main license.
1. Goto Admin >> License Admin >> Candidates
1. Select the newly created license and click on **Verify as new license**.
1. You will be presented with blank page instead of a nice error message saying the license text already exists.

#### Screenshots

snap

### Versions

* Last commit id on master: af99ccd85c3e1dd99844c7478d032608e4d9b0d9

### Logs

```
[Tue Oct 22 12:50:51.398832 2019] [php7:notice] [pid 5681] [client ::1:56862] PHP Notice:  Undefined index: assocObligations in /usr/local/share/fossology/www/ui/admin-license-file.php on line 501, referer: http://localhost/repo/?mod=admin_license&add=y
[Tue Oct 22 12:50:51.398873 2019] [php7:notice] [pid 5681] [client ::1:56862] PHP Stack trace:, referer: http://localhost/repo/?mod=admin_license&add=y
[Tue Oct 22 12:50:51.398879 2019] [php7:notice] [pid 5681] [client ::1:56862] PHP   1. {main}() /usr/local/share/fossology/www/ui/index.php:0, referer: http://localhost/repo/?mod=admin_license&add=y
[Tue Oct 22 12:50:51.398885 2019] [php7:notice] [pid 5681] [client ::1:56862] PHP   2. admin_license_file->execute() /usr/local/share/fossology/www/ui/index.php:64, referer: http://localhost/repo/?mod=admin_license&add=y
[Tue Oct 22 12:50:51.398889 2019] [php7:notice] [pid 5681] [client ::1:56862] PHP   3. admin_license_file->getResponse() /usr/local/share/fossology/lib/php/Plugin/FO_Plugin.php:465, referer: http://localhost/repo/?mod=admin_license&add=y
[Tue Oct 22 12:50:51.398893 2019] [php7:notice] [pid 5681] [client ::1:56862] PHP   4. admin_license_file->Output() /usr/local/share/fossology/lib/php/Plugin/FO_Plugin.php:381, referer: http://localhost/repo/?mod=admin_license&add=y
[Tue Oct 22 12:50:51.398898 2019] [php7:notice] [pid 5681] [client ::1:56862] PHP   5. admin_license_file->Adddb() /usr/local/share/fossology/www/ui/admin-license-file.php:85, referer: http://localhost/repo/?mod=admin_license&add=y
[Tue Oct 22 12:50:51.428366 2019] [php7:notice] [pid 5681] [client ::1:56862] PHP Warning:  Invalid argument supplied for foreach() in /usr/local/share/fossology/www/ui/admin-license-file.php on line 562, referer: http://localhost/repo/?mod=admin_license&add=y
[Tue Oct 22 12:50:51.428513 2019] [php7:notice] [pid 5681] [client ::1:56862] PHP Stack trace:, referer: http://localhost/repo/?mod=admin_license&add=y
[Tue Oct 22 12:50:51.428566 2019] [php7:notice] [pid 5681] [client ::1:56862] PHP   1. {main}() /usr/local/share/fossology/www/ui/index.php:0, referer: http://localhost/repo/?mod=admin_license&add=y
[Tue Oct 22 12:50:51.428575 2019] [php7:notice] [pid 5681] [client ::1:56862] PHP   2. admin_license_file->execute() /usr/local/share/fossology/www/ui/index.php:64, referer: http://localhost/repo/?mod=admin_license&add=y
[Tue Oct 22 12:50:51.428582 2019] [php7:notice] [pid 5681] [client ::1:56862] PHP   3. admin_license_file->getResponse() /usr/local/share/fossology/lib/php/Plugin/FO_Plugin.php:465, referer: http://localhost/repo/?mod=admin_license&add=y
[Tue Oct 22 12:50:51.428590 2019] [php7:notice] [pid 5681] [client ::1:56862] PHP   4. admin_license_file->Output() /usr/local/share/fossology/lib/php/Plugin/FO_Plugin.php:381, referer: http://localhost/repo/?mod=admin_license&add=y
[Tue Oct 22 12:50:51.428596 2019] [php7:notice] [pid 5681] [client ::1:56862] PHP   5. admin_license_file->Adddb() /usr/local/share/fossology/www/ui/admin-license-file.php:85, referer: http://localhost/repo/?mod=admin_license&add=y
[Tue Oct 22 12:54:52.634878 2019] [php7:notice] [pid 5336] [client ::1:56998] PHP Warning:  pg_execute(): Query failed: ERROR:  duplicate key value violates unique constraint &quot;rf_md5unique&quot;\nDETAIL:  Key (rf_md5)=(360c83d04b742b7358d9bc1f5598cc5f) already exists. in /usr/local/share/fossology/lib/php/Db/Driver/Postgres.php on line 70, referer: http://localhost/repo/?mod=admin_license_candidate&rf=770
[Tue Oct 22 12:54:52.634921 2019] [php7:notice] [pid 5336] [client ::1:56998] PHP Stack trace:, referer: http://localhost/repo/?mod=admin_license_candidate&rf=770
[Tue Oct 22 12:54:52.634929 2019] [php7:notice] [pid 5336] [client ::1:56998] PHP   1. {main}() /usr/local/share/fossology/www/ui/index.php:0, referer: http://localhost/repo/?mod=admin_license_candidate&rf=770
[Tue Oct 22 12:54:52.635047 2019] [php7:notice] [pid 5336] [client ::1:56998] PHP   2. Fossology\\UI\\Page\\AdminLicenseCandidate->execute() /usr/local/share/fossology/www/ui/index.php:64, referer: http://localhost/repo/?mod=admin_license_candidate&rf=770
[Tue Oct 22 12:54:52.635056 2019] [php7:notice] [pid 5336] [client ::1:56998] PHP   3. Fossology\\UI\\Page\\AdminLicenseCandidate->getResponse() /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php:271, referer: http://localhost/repo/?mod=admin_license_candidate&rf=770
[Tue Oct 22 12:54:52.635063 2019] [php7:notice] [pid 5336] [client ::1:56998] PHP   4. Fossology\\UI\\Page\\AdminLicenseCandidate->handle() /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php:239, referer: http://localhost/repo/?mod=admin_license_candidate&rf=770
[Tue Oct 22 12:54:52.635070 2019] [php7:notice] [pid 5336] [client ::1:56998] PHP   5. Fossology\\UI\\Page\\AdminLicenseCandidate->verifyCandidate() /usr/local/share/fossology/www/ui/page/AdminLicenseCandidate.php:121, referer: http://localhost/repo/?mod=admin_license_candidate&rf=770
[Tue Oct 22 12:54:52.635076 2019] [php7:notice] [pid 5336] [client ::1:56998] PHP   6. Fossology\\Lib\\Db\\ModernDbManager->getSingleRow() /usr/local/share/fossology/www/ui/page/AdminLicenseCandidate.php:226, referer: http://localhost/repo/?mod=admin_license_candidate&rf=770
[Tue Oct 22 12:54:52.635083 2019] [php7:notice] [pid 5336] [client ::1:56998] PHP   7. Fossology\\Lib\\Db\\ModernDbManager->execute() /usr/local/share/fossology/lib/php/Db/DbManager.php:163, referer: http://localhost/repo/?mod=admin_license_candidate&rf=770
[Tue Oct 22 12:54:52.635089 2019] [php7:notice] [pid 5336] [client ::1:56998] PHP   8. Fossology\\Lib\\Db\\Driver\\Postgres->execute() /usr/local/share/fossology/lib/php/Db/ModernDbManager.php:65, referer: http://localhost/repo/?mod=admin_license_candidate&rf=770
[Tue Oct 22 12:54:52.635115 2019] [php7:notice] [pid 5336] [client ::1:56998] PHP   9. pg_execute() /usr/local/share/fossology/lib/php/Db/Driver/Postgres.php:70, referer: http://localhost/repo/?mod=admin_license_candidate&rf=770
```

### PR DESCRIPTION
**Pull request by adityabisoi**
## Description

If the license text in ```advice license``` already existed in a ```main license```, clicking ```verify as a new license```  showed a blank page.

This is a fix for issue #1507 
### Changes

An error message is shown if the above case occurs.

Closes #1507
Closes #938

### CODE REVIEW

**Comment by adityabisoi** [comment]
@GMishx please review this and suggest any changes.

**Comment by GMishx** [comment]
Thank you for your contribution @adityabisoi, but the changes are effecting verification of licenses which do not have duplicate license text (md5) and license shortname.

Could you please print the error message only when an error occurs?

**Comment by adityabisoi** [comment]
@GMishx I have fixed it. Please review.

File: src/www/ui/page/AdminLicenseCandidate.php [hunk 1]
```diff
@@ -116,6 +116,10 @@ protected function handle(Request $request)
     $ok = true;
     switch ($request->get('do')) {
       case 'verify':
+        if ($vars['suggest_text'] = $suggestLicense['rf_text']) {
```
Comment (GMishx) [inline src/www/ui/page/AdminLicenseCandidate.php]: This method looks bit flawed to me as there is no guarantee that the suggested license will be the exact match for the new license.

What about capturing the error from DB as described in the issue?

Comment (GMishx) [reply src/www/ui/page/AdminLicenseCandidate.php]: Ping to @ag4ums

**Comment by adityabisoi** [comment]
@GMishx thanks, I am working on it. I am trying to understand the codebase. I'll modify it as soon as possible.

**Comment by adityabisoi** [comment]
@GMishx can you please review the changes and suggest me ? Thanks.

File: src/www/ui/page/AdminLicenseCandidate.php [hunk 2]
```diff
@@ -118,7 +118,12 @@ protected function handle(Request $request)
       case 'verify':
       case 'variant':
         $rfParent = ($request->get('do')=='verify') ? $rf : $suggest;
-        $ok = $this->verifyCandidate($rf,$shortname,$rfParent);
+        try{
+          $ok = $this->verifyCandidate($rf,$shortname,$rfParent);
+        } catch (\Throwable $th) {
+          $vars['message'] = 'The license text already exists.';
+          break;
+        }
```
Comment (sjha2048) [inline src/www/ui/page/AdminLicenseCandidate.php]: was just going thru your build logs and found an extra space here, please remove it, this should fix the build error.

Comment (adityabisoi) [reply src/www/ui/page/AdminLicenseCandidate.php]: Corrected.

**Comment by GMishx** [comment]
@adityabisoi, can you please squash you commits to one commit? It would make merging this PR easier.

**Comment by adityabisoi** [comment]
@GMishx I have squashed the commit. Please review. Thanks.
