### PR TITLE
fix(rest): Allows client ID claim to be configurable

### LINKED ISSUE #2204: Make client id as configurable claim for REST auth
### Description

While using client credentials flow for REST API authentication, the client id claim used to authorize request is implementation dependent. Thus it should be configurable by admins.

The `client_id` claim is currently hard coded and should be configurable.

https://github.com/fossology/fossology/blob/ec36f4ed00649437bbde143cf3a78c4bdabe4591/src/www/ui/api/Helper/AuthHelper.php#L318

### PR DESCRIPTION
**Pull request by coder-whale**
## Description

Closes #2204

### Changes

- `src/lib/php/common-sysconfig.php` - Added `OidcClientIdClaim` to system configuration
- `src/www/ui/api/Helper/AuthHelper.php` - Replaced `client_id` with `$SysConf['SYSCONFIG']['OidcClientIdClaim']`

## How to test

- Repopulate db
- Go to "Admin > Customize" in Fossology and edit OIDC Client Id Claim

<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2205"></a>

### CODE REVIEW

File: src/lib/php/common-sysconfig.php [hunk 1]
```diff
@@ -204,65 +204,71 @@ function Populate_sysconfig()
   $valueArray[$variable] = array("'$variable'", "null", "'$oidcPrompt'",
     strval(CONFIG_TYPE_TEXT), "'OauthSupport'", "1", "'$oidcDesc'", "null", "null");
 
+  $variable = "OidcClientIdClaim";
+  $oidcPrompt = _('OIDC Client Id Claim');
+  $oidcDesc = _('e.g. "azp"<br>Client ID claim in the decoded payload.');
+  $valueArray[$variable] = array("'$variable'", "null", "'$oidcPrompt'",
```
Comment (GMishx) [inline src/lib/php/common-sysconfig.php:210]: Let's add a default value for this to prevent unwanted errors in deployments.
```suggestion
  $valueArray[$variable] = array("'$variable'", "'client-id'", "'$oidcPrompt'",
```

**Review by GMishx — APPROVED** [review]
Tested, working as expected.

**Comment by coder-whale** [comment]
changes done

**Review by GMishx — APPROVED** [review]
Changes looks good. Working as expected.
