### PR TITLE
fix(log): fix warnings from apache error log

### LINKED ISSUE #1544: PHP warnings in delagent
### Description

While deleting 3 packages, delagent throw following PHP warnings.

### Versions

* Operating System (lsb_release -a): Ubuntu 16.04
* PHP version: 7.3

#### Apache logs

```
PHP Warning:  array_count_values(): Can only count STRING and INTEGER values! in /usr/local/share/fossology/delagent/ui/Page/AdminUploadDelete.php on line 160, referer: http://localhost/?mod=admin_upload_delete
PHP Stack trace:, referer: http://localhost/?mod=admin_upload_delete
PHP   1. {main}() /usr/local/share/fossology/www/ui/index.php:0, referer: http://localhost/?mod=admin_upload_delete
PHP   2. Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete->execute() /usr/local/share/fossology/www/ui/index.php:64, referer: http://localhost/?mod=admin_upload_delete
PHP   3. Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete->getResponse() /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php:271, referer: http://localhost/?mod=admin_upload_delete
PHP   4. Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete->handle() /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php:239, referer: http://localhost/?mod=admin_upload_delete
PHP   5. Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete->initDeletion() /usr/local/share/fossology/delagent/ui/Page/AdminUploadDelete.php:107, referer: http://localhost/?mod=admin_upload_delete
PHP   6. array_count_values() /usr/local/share/fossology/delagent/ui/Page/AdminUploadDelete.php:160, referer: http://localhost/?mod=admin_upload_delete
PHP Warning:  array_count_values(): Can only count STRING and INTEGER values! in /usr/local/share/fossology/delagent/ui/Page/AdminUploadDelete.php on line 160, referer: http://localhost/?mod=admin_upload_delete
PHP Stack trace:, referer: http://localhost/?mod=admin_upload_delete
PHP   1. {main}() /usr/local/share/fossology/www/ui/index.php:0, referer: http://localhost/?mod=admin_upload_delete
PHP   2. Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete->execute() /usr/local/share/fossology/www/ui/index.php:64, referer: http://localhost/?mod=admin_upload_delete
PHP   3. Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete->getResponse() /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php:271, referer: http://localhost/?mod=admin_upload_delete
PHP   4. Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete->handle() /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php:239, referer: http://localhost/?mod=admin_upload_delete
PHP   5. Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete->initDeletion() /usr/local/share/fossology/delagent/ui/Page/AdminUploadDelete.php:107, referer: http://localhost/?mod=admin_upload_delete
PHP   6. array_count_values() /usr/local/share/fossology/delagent/ui/Page/AdminUploadDelete.php:160, referer: http://localhost/?mod=admin_upload_delete
PHP Warning:  array_count_values(): Can only count STRING and INTEGER values! in /usr/local/share/fossology/delagent/ui/Page/AdminUploadDelete.php on line 160, referer: http://localhost/?mod=admin_upload_delete
PHP Stack trace:, referer: http://localhost/?mod=admin_upload_delete
PHP   1. {main}() /usr/local/share/fossology/www/ui/index.php:0, referer: http://localhost/?mod=admin_upload_delete
PHP   2. Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete->execute() /usr/local/share/fossology/www/ui/index.php:64, referer: http://localhost/?mod=admin_upload_delete
PHP   3. Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete->getResponse() /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php:271, referer: http://localhost/?mod=admin_upload_delete
PHP   4. Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete->handle() /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php:239, referer: http://localhost/?mod=admin_upload_delete
PHP   5. Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete->initDeletion() /usr/local/share/fossology/delagent/ui/Page/AdminUploadDelete.php:107, referer: http://localhost/?mod=admin_upload_delete
PHP   6. array_count_values() /usr/local/share/fossology/delagent/ui/Page/AdminUploadDelete.php:160, referer: http://localhost/?mod=admin_upload_delete
PHP Warning:  array_count_values(): Can only count STRING and INTEGER values! in /usr/local/share/fossology/delagent/ui/Page/AdminUploadDelete.php on line 160, referer: http://localhost/?mod=admin_upload_delete
PHP Stack trace:, referer: http://localhost/?mod=admin_upload_delete
PHP   1. {main}() /usr/local/share/fossology/www/ui/index.php:0, referer: http://localhost/?mod=admin_upload_delete
PHP   2. Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete->execute() /usr/local/share/fossology/www/ui/index.php:64, referer: http://localhost/?mod=admin_upload_delete
PHP   3. Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete->getResponse() /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php:271, referer: http://localhost/?mod=admin_upload_delete
PHP   4. Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete->handle() /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php:239, referer: http://localhost/?mod=admin_upload_delete
PHP   5. Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete->initDeletion() /usr/local/share/fossology/delagent/ui/Page/AdminUploadDelete.php:107, referer: http://localhost/?mod=admin_upload_delete
PHP   6. array_count_values() /usr/local/share/fossology/delagent/ui/Page/AdminUploadDelete.php:160, referer: http://localhost/?mod=admin_upload_delete
PHP Warning:  array_count_values(): Can only count STRING and INTEGER values! in /usr/local/share/fossology/delagent/ui/Page/AdminUploadDelete.php on line 160, referer: http://localhost/?mod=admin_upload_delete
PHP Stack trace:, referer: http://localhost/?mod=admin_upload_delete
PHP   1. {main}() /usr/local/share/fossology/www/ui/index.php:0, referer: http://localhost/?mod=admin_upload_delete
PHP   2. Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete->execute() /usr/local/share/fossology/www/ui/index.php:64, referer: http://localhost/?mod=admin_upload_delete
PHP   3. Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete->getResponse() /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php:271, referer: http://localhost/?mod=admin_upload_delete
PHP   4. Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete->handle() /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php:239, referer: http://localhost/?mod=admin_upload_delete
PHP   5. Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete->initDeletion() /usr/local/share/fossology/delagent/ui/Page/AdminUploadDelete.php:107, referer: http://localhost/?mod=admin_upload_delete
PHP   6. array_count_values() /usr/local/share/fossology/delagent/ui/Page/AdminUploadDelete.php:160, referer: http://localhost/?mod=admin_upload_delete
PHP Notice:  Object of class Fossology\\DelAgent\\UI\\DeleteResponse could not be converted to int in /usr/local/share/fossology/delagent/ui/Page/AdminUploadDelete.php on line 161, referer: http://localhost/?mod=admin_upload_delete
PHP Stack trace:, referer: http://localhost/?mod=admin_upload_delete
PHP   1. {main}() /usr/local/share/fossology/www/ui/index.php:0, referer: http://localhost/?mod=admin_upload_delete
PHP   2. Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete->execute() /usr/local/share/fossology/www/ui/index.php:64, referer: http://localhost/?mod=admin_upload_delete
PHP   3. Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete->getResponse() /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php:271, referer: http://localhost/?mod=admin_upload_delete
PHP   4. Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete->handle() /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php:239, referer: http://localhost/?mod=admin_upload_delete
PHP   5. Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete->initDeletion() /usr/local/share/fossology/delagent/ui/Page/AdminUploadDelete.php:107, referer: http://localhost/?mod=admin_upload_delete
PHP   6. in_array() /usr/local/share/fossology/delagent/ui/Page/AdminUploadDelete.php:161, referer: http://localhost/?mod=admin_upload_delete
PHP Notice:  Undefined offset: 1 in /usr/local/share/fossology/delagent/ui/Page/AdminUploadDelete.php on line 163, referer: http://localhost/?mod=admin_upload_delete
PHP Stack trace:, referer: http://localhost/?mod=admin_upload_delete
PHP   1. {main}() /usr/local/share/fossology/www/ui/index.php:0, referer: http://localhost/?mod=admin_upload_delete
PHP   2. Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete->execute() /usr/local/share/fossology/www/ui/index.php:64, referer: http://localhost/?mod=admin_upload_delete
PHP   3. Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete->getResponse() /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php:271, referer: http://localhost/?mod=admin_upload_delete
PHP   4. Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete->handle() /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php:239, referer: http://localhost/?mod=admin_upload_delete
PHP   5. Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete->initDeletion() /usr/local/share/fossology/delagent/ui/Page/AdminUploadDelete.php:107, referer: http://localhost/?mod=admin_upload_delete
PHP Notice:  Object of class Fossology\\DelAgent\\UI\\DeleteResponse could not be converted to int in /usr/local/share/fossology/delagent/ui/Page/AdminUploadDelete.php on line 166, referer: http://localhost/?mod=admin_upload_delete
PHP Stack trace:, referer: http://localhost/?mod=admin_upload_delete
PHP   1. {main}() /usr/local/share/fossology/www/ui/index.php:0, referer: http://localhost/?mod=admin_upload_delete
PHP   2. Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete->execute() /usr/local/share/fossology/www/ui/index.php:64, referer: http://localhost/?mod=admin_upload_delete
PHP   3. Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete->getResponse() /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php:271, referer: http://localhost/?mod=admin_upload_delete
PHP   4. Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete->handle() /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php:239, referer: http://localhost/?mod=admin_upload_delete
PHP   5. Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete->initDeletion() /usr/local/share/fossology/delagent/ui/Page/AdminUploadDelete.php:107, referer: http://localhost/?mod=admin_upload_delete
PHP   6. in_array() /usr/local/share/fossology/delagent/ui/Page/AdminUploadDelete.php:166, referer: http://localhost/?mod=admin_upload_delete
PHP Notice:  Object of class Fossology\\DelAgent\\UI\\DeleteResponse could not be converted to int in /usr/local/share/fossology/delagent/ui/Page/AdminUploadDelete.php on line 166, referer: http://localhost/?mod=admin_upload_delete
PHP Stack trace:, referer: http://localhost/?mod=admin_upload_delete
PHP   1. {main}() /usr/local/share/fossology/www/ui/index.php:0, referer: http://localhost/?mod=admin_upload_delete
PHP   2. Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete->execute() /usr/local/share/fossology/www/ui/index.php:64, referer: http://localhost/?mod=admin_upload_delete
PHP   3. Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete->getResponse() /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php:271, referer: http://localhost/?mod=admin_upload_delete
PHP   4. Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete->handle() /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php:239, referer: http://localhost/?mod=admin_upload_delete
PHP   5. Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete->initDeletion() /usr/local/share/fossology/delagent/ui/Page/AdminUploadDelete.php:107, referer: http://localhost/?mod=admin_upload_delete
PHP   6. in_array() /usr/local/share/fossology/delagent/ui/Page/AdminUploadDelete.php:166, referer: http://localhost/?mod=admin_upload_delete
PHP Notice:  Object of class Fossology\\DelAgent\\UI\\DeleteResponse could not be converted to int in /usr/local/share/fossology/delagent/ui/Page/AdminUploadDelete.php on line 166, referer: http://localhost/?mod=admin_upload_delete
PHP Stack trace:, referer: http://localhost/?mod=admin_upload_delete
PHP   1. {main}() /usr/local/share/fossology/www/ui/index.php:0, referer: http://localhost/?mod=admin_upload_delete
PHP   2. Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete->execute() /usr/local/share/fossology/www/ui/index.php:64, referer: http://localhost/?mod=admin_upload_delete
PHP   3. Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete->getResponse() /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php:271, referer: http://localhost/?mod=admin_upload_delete
PHP   4. Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete->handle() /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php:239, referer: http://localhost/?mod=admin_upload_delete
PHP   5. Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete->initDeletion() /usr/local/share/fossology/delagent/ui/Page/AdminUploadDelete.php:107, referer: http://localhost/?mod=admin_upload_delete
PHP   6. in_array() /usr/local/share/fossology/delagent/ui/Page/AdminUploadDelete.php:166, referer: http://localhost/?mod=admin_upload_delete
PHP Notice:  Object of class Fossology\\DelAgent\\UI\\DeleteResponse could not be converted to int in /usr/local/share/fossology/delagent/ui/Page/AdminUploadDelete.php on line 166, referer: http://localhost/?mod=admin_upload_delete
PHP Stack trace:, referer: http://localhost/?mod=admin_upload_delete
PHP   1. {main}() /usr/local/share/fossology/www/ui/index.php:0, referer: http://localhost/?mod=admin_upload_delete
PHP   2. Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete->execute() /usr/local/share/fossology/www/ui/index.php:64, referer: http://localhost/?mod=admin_upload_delete
PHP   3. Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete->getResponse() /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php:271, referer: http://localhost/?mod=admin_upload_delete
PHP   4. Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete->handle() /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php:239, referer: http://localhost/?mod=admin_upload_delete
PHP   5. Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete->initDeletion() /usr/local/share/fossology/delagent/ui/Page/AdminUploadDelete.php:107, referer: http://localhost/?mod=admin_upload_delete
PHP   6. in_array() /usr/local/share/fossology/delagent/ui/Page/AdminUploadDelete.php:166, referer: http://localhost/?mod=admin_upload_delete
PHP Notice:  Object of class Fossology\\DelAgent\\UI\\DeleteResponse could not be converted to int in /usr/local/share/fossology/delagent/ui/Page/AdminUploadDelete.php on line 166, referer: http://localhost/?mod=admin_upload_delete
PHP Stack trace:, referer: http://localhost/?mod=admin_upload_delete
PHP   1. {main}() /usr/local/share/fossology/www/ui/index.php:0, referer: http://localhost/?mod=admin_upload_delete
PHP   2. Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete->execute() /usr/local/share/fossology/www/ui/index.php:64, referer: http://localhost/?mod=admin_upload_delete
PHP   3. Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete->getResponse() /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php:271, referer: http://localhost/?mod=admin_upload_delete
PHP   4. Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete->handle() /usr/local/share/fossology/lib/php/Plugin/DefaultPlugin.php:239, referer: http://localhost/?mod=admin_upload_delete
PHP   5. Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete->initDeletion() /usr/local/share/fossology/delagent/ui/Page/AdminUploadDelete.php:107, referer: http://localhost/?mod=admin_upload_delete
PHP   6. in_array() /usr/local/share/fossology/delagent/ui/Page/AdminUploadDelete.php:166, referer: http://localhost/?mod=admin_upload_delete
```

### PR DESCRIPTION
**Pull request by shaheemazmalmmd**
## Description

Fixed apache error log.

## How to test

Needs general testing

closes #1544

### CODE REVIEW

File: src/delagent/ui/DeleteMessages.php [hunk 1]
```diff
@@ -24,7 +24,7 @@
  */
 abstract class DeleteMessages
 {
-  const NO_PERMISSION = 0; /**< You don't have permissions to delete the upload */
   const SCHEDULING_FAILED = 1; /**< Deletion Scheduling failed */
   const SUCCESS =  2; /**< Deletion added to job queue */
+  const NO_PERMISSION = 3; /**< You don't have permissions to delete the upload */
```
Comment (GMishx) [inline src/delagent/ui/DeleteMessages.php]: Please update the messages in `src/delagent/ui/DeleteResponse.php` accordingly if changing the codes.

**Comment by ag4ums** [comment]
Not able to reproduce the issue... @GMishx please look into it
